export const Bulbasaur = {
    id: 'bulbasaur',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Grass',
    headline: 'Bulbasaur',
    description: 'There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.',
    buttonLabel: 'Catch',
    imgStart: false,
    img: require('../../img/bulbasaur.png'),
    alt: 'Pokeball',
    dark: true,
    primary: true,
    darkText: true,
}

export const Charmander = {
    id: 'charmander',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Fire',
    headline: 'Charmander ',
    description: 'It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.',
    buttonLabel: 'Catch',
    imgStart: true,
    img: require('../../img/charmander.png'),
    alt: 'Pokeball',
    dark: true,
    primary: true,
    darkText: false,
}

export const Squirtle = {
    id: 'squirtle',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Water',
    headline: 'Squirtle ',
    description: 'When it retracts its long neck into its shell, it squirts out water with vigorous force.',
    buttonLabel: 'Catch',
    imgStart: false,
    img: require('../../img/squirtle.png'),
    alt: 'Pokeball',
    dark: true,
    primary: true,
    darkText: true,
}